In [45]:
import pandas as pd

In [46]:
pokemon_df = pd.read_csv('pokemonscraper\pokemon.csv', sep=',')
#oldpokemon_df = pd.read_csv('pokemonscraper\pokemon_old.csv', sep=',')

In [47]:
pokemon_df.head()

,Pokedex Number,Base Pokemon,Variant Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,...,Speed,Generation,Mega,Paradox,Legendary,Pseudo-legendary,Ultrabeast,Regional Form,Mythical,img_name
0,15,Beedrill,Beedrill,Bug,Poison,395,65,90,40,45,...,75,1,False,False,False,False,False,False,False,0015_Beedrill.png
1,15,Beedrill,Mega Beedrill,Bug,Poison,495,65,150,40,15,...,145,1,True,False,False,False,False,False,False,0015_Mega Beedrill.png
2,1,Bulbasaur,Bulbasaur,Grass,Poison,318,45,49,49,65,...,45,1,False,False,False,False,False,False,False,0001_Bulbasaur.png
3,21,Spearow,Spearow,Normal,Flying,262,40,60,30,31,...,70,1,False,False,False,False,False,False,False,0021_Spearow.png
4,16,Pidgey,Pidgey,Normal,Flying,251,40,45,40,35,...,56,1,False,False,False,False,False,False,False,0016_Pidgey.png

In [48]:
pokemon_df.count()

Pokedex Number      1173
Base Pokemon        1173
Variant Name        1173
Type 1              1173
Type 2               637
Total               1173
HP                  1173
Attack              1173
Defense             1173
Sp. Atk             1173
Sp. Def             1173
Speed               1173
Generation          1173
Mega                1173
Paradox             1173
Legendary           1173
Pseudo-legendary    1173
Ultrabeast          1173
Regional Form       1173
Mythical            1173
img_name            1173
dtype: int64

1010 unique values for Pokedex number is expected

In [49]:
pokemon_df['Pokedex Number'].nunique()

1010

The entries for the following pokemon need to be corrected:
 - Pikachu
 - Darmanitan
 - Pumpkaboo
 - Gourgeist

In [50]:
pokemon_df[pokemon_df['Pokedex Number']==25]
pik1 = pokemon_df.loc[pokemon_df['Variant Name'] == 'Cosplay Pikachu'].index[0]
pik2 = pokemon_df.loc[pokemon_df['Variant Name'] == 'Pikachu in a cap'].index[0]
pik3 = pokemon_df.loc[pokemon_df['Variant Name'] == 'Partner Pikachu'].index[0]
print(pik1)

1169

In [51]:
pik1 = pokemon_df.loc[pokemon_df['Variant Name'] == 'Pikachu'].index[0]
pik2 = pokemon_df.loc[pokemon_df['Variant Name'] == 'Pikachu in a cap'].index[0]
pik3 = pokemon_df.loc[pokemon_df['Variant Name'] == 'Partner Pikachu'].index[0]
pokemon_df[pokemon_df['Pokedex Number']==25].drop([pokemon_df.index[pik1], pokemon_df.index[pik2], pokemon_df.index[pik3]]).replace(['Cosplay Pikachu'], 'Pikachu').replace(['0025_Cosplay Pikachu.png'], '0025_Pikachu.png')

,Pokedex Number,Base Pokemon,Variant Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,...,Speed,Generation,Mega,Paradox,Legendary,Pseudo-legendary,Ultrabeast,Regional Form,Mythical,img_name
1169,25,Pikachu,Pikachu,Electric,NaN,320,35,55,40,50,...,90,1,False,False,False,False,False,False,False,0025_Pikachu.png

In [52]:
pokemon_df = pokemon_df.drop([pokemon_df.index[pik1], pokemon_df.index[pik2], pokemon_df.index[pik3]])
pik = pokemon_df.loc[pokemon_df['Variant Name'] == 'Cosplay Pikachu'].index[0]
pokemon_df.loc[[pik], ['Variant Name']]=['Pikachu']
pokemon_df.loc[[pik], ['img_name']]=['0025_Pikachu.png']

In [53]:
pokemon_df[pokemon_df['Pokedex Number']==25]

,Pokedex Number,Base Pokemon,Variant Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,...,Speed,Generation,Mega,Paradox,Legendary,Pseudo-legendary,Ultrabeast,Regional Form,Mythical,img_name
1169,25,Pikachu,Pikachu,Electric,NaN,320,35,55,40,50,...,90,1,False,False,False,False,False,False,False,0025_Pikachu.png

Pikachu entry corrected and removed extra entries

In [54]:
pokemon_df[pokemon_df['Pokedex Number']==555]

,Pokedex Number,Base Pokemon,Variant Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,...,Speed,Generation,Mega,Paradox,Legendary,Pseudo-legendary,Ultrabeast,Regional Form,Mythical,img_name
539,555,Darmanitan,Darmanitan Standard Mode,Fire,NaN,480,105,140,55,30,...,95,5,False,False,False,False,False,False,False,0555_Darmanitan Standard Mode.png
540,555,Darmanitan,Darmanitan Galarian Standard Mode,Ice,NaN,540,105,30,105,140,...,55,5,False,False,False,False,False,True,False,0555_Darmanitan Galarian Standard Mode.png
541,555,Darmanitan,Darmanitan Zen Mode,Fire,Psychic,540,105,160,55,30,...,135,5,False,False,False,False,False,False,False,0555_Darmanitan Zen Mode.png
542,555,Darmanitan,Darmanitan Galarian Zen Mode,Ice,Fire,480,105,140,55,30,...,95,5,False,False,False,False,False,True,False,0555_Darmanitan Galarian Zen Mode.png

In [55]:
dar1 = pokemon_df.loc[pokemon_df['Variant Name'] == 'Darmanitan Galarian Standard Mode'].index[0]
dar2 = pokemon_df.loc[pokemon_df['Variant Name'] == 'Darmanitan Galarian Zen Mode'].index[0]
dar3 = pokemon_df.loc[pokemon_df['Variant Name'] == 'Darmanitan Zen Mode'].index[0]
pokemon_df.loc[[dar1], ['Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]=[480, 105, 140, 55, 30, 55, 95]
pokemon_df.loc[[dar2], ['Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]=[540, 105, 160, 55, 30, 55, 135]
pokemon_df.loc[[dar3], ['Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]=[540, 105, 30, 105, 140, 105, 55]

In [56]:
pokemon_df[pokemon_df['Pokedex Number']==555]

,Pokedex Number,Base Pokemon,Variant Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,...,Speed,Generation,Mega,Paradox,Legendary,Pseudo-legendary,Ultrabeast,Regional Form,Mythical,img_name
539,555,Darmanitan,Darmanitan Standard Mode,Fire,NaN,480,105,140,55,30,...,95,5,False,False,False,False,False,False,False,0555_Darmanitan Standard Mode.png
540,555,Darmanitan,Darmanitan Galarian Standard Mode,Ice,NaN,480,105,140,55,30,...,95,5,False,False,False,False,False,True,False,0555_Darmanitan Galarian Standard Mode.png
541,555,Darmanitan,Darmanitan Zen Mode,Fire,Psychic,540,105,30,105,140,...,55,5,False,False,False,False,False,False,False,0555_Darmanitan Zen Mode.png
542,555,Darmanitan,Darmanitan Galarian Zen Mode,Ice,Fire,540,105,160,55,30,...,135,5,False,False,False,False,False,True,False,0555_Darmanitan Galarian Zen Mode.png

Darmanitan entries have been corrected and now the missing sizes for Gourgeist and Pumpkaboo will be added and corrected

In [57]:
gourgeist = pokemon_df.loc[pokemon_df['Variant Name'] == 'Gourgeist Super Size'].index[0]
pokemon_df.loc[[gourgeist], ['Variant Name']]=['Gourgeist Average Size']
missing_sizes = {
    'Pokedex Number': [711, 711, 711],
    'Base Pokemon': ['Gourgeist', 'Gourgeist', 'Gourgeist'],
    'Variant Name': ['Gourgeist Small Size', 'Gourgeist Large Size', 'Gourgeist Super Size'],
    'Type 1': ['Ghost', 'Ghost', 'Ghost'],
    'Type 2': ['Grass', 'Grass', 'Grass'],
    'Total': [494, 494, 494],
    'HP': [55, 75, 85],
    'Attack': [85, 95, 100],
    'Defense': [122, 122, 122],
    'Sp. Atk': [58, 58, 58],
    'Sp. Def': [75, 75, 75],
    'Speed': [99, 69, 54],
    'Generation': [6, 6, 6],
    'Mega': [False, False, False],
    'Paradox': [False, False, False],
    'Legendary': [False, False, False],
    'Pseudo-legendary': [False, False, False],
    'Ultrabeast': [False, False, False],
    'Regional Form': [False, False, False],
    'Mythical': [False, False, False],
    'img_name': ['0711_Gourgeist Super Size.png', '0711_Gourgeist Super Size.png', '0711_Gourgeist Super Size.png']
}
missing_df = pd.DataFrame(missing_sizes)
pokemon_df = pd.concat([pokemon_df, missing_df], axis=0)

In [58]:
pokemon_df[pokemon_df['Pokedex Number']==711]

,Pokedex Number,Base Pokemon,Variant Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,...,Speed,Generation,Mega,Paradox,Legendary,Pseudo-legendary,Ultrabeast,Regional Form,Mythical,img_name
366,711,Gourgeist,Gourgeist Average Size,Ghost,Grass,494,65,90,122,58,...,84,6,False,False,False,False,False,False,False,0711_Gourgeist Super Size.png
0,711,Gourgeist,Gourgeist Small Size,Ghost,Grass,494,55,85,122,58,...,99,6,False,False,False,False,False,False,False,0711_Gourgeist Super Size.png
1,711,Gourgeist,Gourgeist Large Size,Ghost,Grass,494,75,95,122,58,...,69,6,False,False,False,False,False,False,False,0711_Gourgeist Super Size.png
2,711,Gourgeist,Gourgeist Super Size,Ghost,Grass,494,85,100,122,58,...,54,6,False,False,False,False,False,False,False,0711_Gourgeist Super Size.png

Gourgeist now corrected

In [59]:
pumpkaboo = pokemon_df.loc[pokemon_df['Variant Name'] == 'Pumpkaboo Super Size'].index[0]
pokemon_df.loc[[pumpkaboo], ['Variant Name']]=['Pumpkaboo Average Size']
missing_sizes = {
    'Pokedex Number': [710, 710, 710],
    'Base Pokemon': ['Pumpkaboo', 'Pumpkaboo', 'Pumpkaboo'],
    'Variant Name': ['Pumpkaboo Small Size', 'Pumpkaboo Large Size', 'Pumpkaboo Super Size'],
    'Type 1': ['Ghost', 'Ghost', 'Ghost'],
    'Type 2': ['Grass', 'Grass', 'Grass'],
    'Total': [335, 335, 335],
    'HP': [44, 54, 59],
    'Attack': [66, 66, 66],
    'Defense': [70, 70, 70],
    'Sp. Atk': [44, 44, 44],
    'Sp. Def': [55, 55, 55],
    'Speed': [56, 46, 41],
    'Generation': [6, 6, 6],
    'Mega': [False, False, False],
    'Paradox': [False, False, False],
    'Legendary': [False, False, False],
    'Pseudo-legendary': [False, False, False],
    'Ultrabeast': [False, False, False],
    'Regional Form': [False, False, False],
    'Mythical': [False, False, False],
    'img_name': ['0710_Pumpkaboo Super Size.png', '0710_Pumpkaboo Super Size.png', '0710_Pumpkaboo Super Size.png']
}
missing_df = pd.DataFrame(missing_sizes)
pokemon_df = pd.concat([pokemon_df, missing_df], axis=0)

In [60]:
pokemon_df[pokemon_df['Pokedex Number']==710]

,Pokedex Number,Base Pokemon,Variant Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,...,Speed,Generation,Mega,Paradox,Legendary,Pseudo-legendary,Ultrabeast,Regional Form,Mythical,img_name
367,710,Pumpkaboo,Pumpkaboo Average Size,Ghost,Grass,335,49,66,70,44,...,51,6,False,False,False,False,False,False,False,0710_Pumpkaboo Super Size.png
0,710,Pumpkaboo,Pumpkaboo Small Size,Ghost,Grass,335,44,66,70,44,...,56,6,False,False,False,False,False,False,False,0710_Pumpkaboo Super Size.png
1,710,Pumpkaboo,Pumpkaboo Large Size,Ghost,Grass,335,54,66,70,44,...,46,6,False,False,False,False,False,False,False,0710_Pumpkaboo Super Size.png
2,710,Pumpkaboo,Pumpkaboo Super Size,Ghost,Grass,335,59,66,70,44,...,41,6,False,False,False,False,False,False,False,0710_Pumpkaboo Super Size.png

Pumpkaboo now corrected

In [61]:
pokemon_df[pokemon_df['Pokedex Number']==479]
fan = pokemon_df.loc[pokemon_df['Variant Name'] == 'Fan Rotom'].index[0]
pokemon_df.loc[[fan], ['Type 2']]=['Flying']

In [64]:
pokemon_df[pokemon_df['Pokedex Number']==479]

,Pokedex Number,Base Pokemon,Variant Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,...,Speed,Generation,Mega,Paradox,Legendary,Pseudo-legendary,Ultrabeast,Regional Form,Mythical,img_name
626,479,Rotom,Rotom,Electric,Ghost,440,50,50,77,95,...,91,4,False,False,False,False,False,False,False,0479_Rotom.png
627,479,Rotom,Heat Rotom,Electric,Fire,520,50,65,107,105,...,86,4,False,False,False,False,False,False,False,0479_Heat Rotom.png
628,479,Rotom,Wash Rotom,Electric,Water,520,50,65,107,105,...,86,4,False,False,False,False,False,False,False,0479_Wash Rotom.png
629,479,Rotom,Frost Rotom,Electric,Ice,520,50,65,107,105,...,86,4,False,False,False,False,False,False,False,0479_Frost Rotom.png
630,479,Rotom,Mow Rotom,Electric,Grass,520,50,65,107,105,...,86,4,False,False,False,False,False,False,False,0479_Mow Rotom.png
631,479,Rotom,Fan Rotom,Electric,Flying,520,50,65,107,105,...,86,4,False,False,False,False,False,False,False,0479_Fan Rotom.png

In [63]:
#pokemon_df.iloc[[635], ['Variant Name', 'Type 2', 'img_name']] =['Mow Rotom', 'Grass', '0479_Mow Rotom.png']
mow = pokemon_df.loc[(pokemon_df['Variant Name'] == 'Frost Rotom') & (pokemon_df['Type 2'] == 'Flying')].index[0]
pokemon_df.loc[[mow], ['Variant Name', 'Type 2', 'img_name']] =['Mow Rotom', 'Grass', '0479_Mow Rotom.png']

In [42]:
pokemon_df = pokemon_df.sort_values(by=['Pokedex Number', 'Total'], ascending=True)

In [43]:
#filter = pokemon_df['Group'].apply(lambda x: 'Regional Form' in x)
pokemon_df.head()

,Pokedex Number,Base Pokemon,Variant Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,...,Speed,Generation,Mega,Paradox,Legendary,Pseudo-legendary,Ultrabeast,Regional Form,Mythical,img_name
2,1,Bulbasaur,Bulbasaur,Grass,Poison,318,45,49,49,65,...,45,1,False,False,False,False,False,False,False,0001_Bulbasaur.png
26,2,Ivysaur,Ivysaur,Grass,Poison,405,60,62,63,80,...,60,1,False,False,False,False,False,False,False,0002_Ivysaur.png
24,3,Venusaur,Venusaur,Grass,Poison,525,80,82,83,100,...,80,1,False,False,False,False,False,False,False,0003_Venusaur.png
25,3,Venusaur,Mega Venusaur,Grass,Poison,625,80,100,123,122,...,80,1,True,False,False,False,False,False,False,0003_Mega Venusaur.png
30,4,Charmander,Charmander,Fire,NaN,309,39,52,43,60,...,65,1,False,False,False,False,False,False,False,0004_Charmander.png

In [44]:
pokemon_df.to_csv('pokemon_cleaned.csv', index=False)